[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route /api/search to our function
[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

# SPA fallback so client routes never 404 (fine even if you don't use routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
